### ISSUE TITLE
two-factor apple id

### ISSUE THREAD

**Issue by Zjemm** [scintill/macos-server-apns-certs#3]
I'm trying this today as my certs are about to expire
BUT
i'm getting messages my password is invalid.

so i thought, ofcourse....i have two factor auth enabled (can't be disabled)
so i made a special APP password and used that, but still i'm getting password is invalid messages.

anyone tried this? with 2fa>

**Comment by scintill** [comment]
I'll see if I can experiment with 2fa.

These things might be obvious to you, but some ideas: I wonder if you are accidentally adding whitespace to your password when you hash it -- **don't** press enter at the end, just Ctrl-D until the hash appears. Also, ensure you aren't copying part of your password as the hash (on my system at least, the hash starts immediately after the last character of the password.) Hope this helps.

**Comment by Zjemm** [comment]
yes i made sure to exactly typed the password and do a ctrl-d twice

the app password looks like this example: znjj-aaac-rgtz-dvgd

but it does not seem to work

curl -i --data-binary @request-body -H 'Content-Type: text/x-xml-plist' --user-agent 'Servermgrd%20Plugin/6.0 CFNetwork/811.11 Darwin/16.7.0 (x86_64)' https://identity.apple.com/pushcert/caservice/new -H 'Accept: */*' -H 'Accept-Language: en-us' | tee response
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15254  100  1116  100 14138    985  12489  0:00:01  0:00:01 --:--:-- 13475
HTTP/1.1 100 Continue

HTTP/1.1 200
Server: Apple
Date: Thu, 10 Sep 2020 20:05:30 GMT
Content-Type: text/x-xml-plist
Content-Length: 1116
Connection: keep-alive
Cache-Control: no-cache
Strict-Transport-Security: max-age=31536000; includeSubdomains
X-Frame-Options: SAMEORIGIN
Host: identity.apple.com
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubdomains
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Host: identity.apple.com
X-Frame-Options: SAMEORIGIN

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Response</key>
    <dict>
        <key>Status</key>
        <dict>
            <key>ErrorDescription</key>
            <string>Invalid account name and password. Please verify the account name - password</string>
            <key>ErrorMessage</key>
            <string>Account Name - Password invalid.</string>
            <key>ErrorCode</key>
            <integer>-80004</integer>
        </dict>
    </dict>
    <key>Header</key>
    <dict>
        <key>ClientIPAddress</key>
        <string>1</string>
        <key>LanguagePreference</key>
        <string>1</string>
        <key>TransactionId</key>
        <string>1</string>
        <key>ClientOSVersion</key>
        <string>2.1</string>
        <key>ClientOSName</key>
        <string>MAC OSX</string>
        <key>ClientApplicationName</key>
        <string>XServer</string>
        <key>ClientApplicationCredential</key>
        <string>1</string>
    </dict>
</dict>
</plist>

**Comment by pagaille** [comment]
Strange. I have 2fa activated and didn’t had that problem.

**Comment by Zjemm** [comment]
did you use a app password? or just your normal password?

could it be the hasing might be because of a different distro??

**Comment by pagaille** [comment]
Nope. Usual Apple password. I ran the tool on Linux.

**Comment by scintill** [comment]
Is there whitespace in your Apple ID account name? Check `PushCertRequestPlist` and verify it has something like this with no space in the XML tags:

```
			<key>AccountName</key>
			<string>name@example.com</string>
```

**Comment by Zjemm** [comment]
I’ll check it tonight when I’m home, thanks for thinking with me

**Comment by Zjemm** [comment]
well it must have been the username as the password hash was ok
it works now :)  thanks for the help.

and indeed, no 2FA needed, just the normal appleID password

**Comment by scintill** [comment]
Glad you got it working. Thanks for the info on how 2FA works with this. I'll add it to the readme.

**Comment by titanism** [comment]
Can't seem to get it working with either app password or regular password while 2FA is enabled.  Were there any workarounds?

**Comment by titanism** [comment]
Okay it appears that this library no longer properly generates the hash required.

Instead I generated a hash using this approach:

```sh
git clone https://github.com/freswa/dovecot-xaps-daemon.git
cd dovecot-xaps-daemon
go build ./cmd/xapsd/xapsd.go
./xapsd -pass
```

**Comment by titanism** [comment]
Behind the scenes it does this:

<https://github.com/freswa/dovecot-xaps-daemon/blob/abce2f14cf1b5afa56329ebb4d923c9c2aebdfe3/cmd/xapsd/xapsd.go#L73-L83>

**Comment by titanism** [comment]
You can simply instead do this:

```sh
echo -n "yourpasswordhere" | sha256sum
```

To get the value
