### ISSUE TITLE
Not working anymore ?

### ISSUE THREAD

**Issue by pagaille** [scintill/macos-server-apns-certs#5]
I'm pretty sure that I did everything right, it was working previously, but now I consistently receive that answer from apple :  

```
<key>Response</key>
    <dict>
        <key>Status</key>
        <dict>
            <key>ErrorDescription</key>
            <string>Invalid account name and password. Please verify the account name - password</string>
            <key>ErrorMessage</key>
            <string>Account Name - Password invalid.</string>
            <key>ErrorCode</key>
            <integer>-80004</integer>
        </dict>
    </dict>

```

Is it me or them ?

NB : after typing my password I had to hit Return before Ctrl-d ctrl-d otherwise nothing happened.

**Comment by pagaille** [comment]
EDIT : Solved.

I had to hit **THREE** times CTRL-D. Don't know why. I'm running the tool under CentOS 7.

**Comment by titanism** [comment]
You can simply instead do this:

```sh
echo -n "yourpasswordhere" | sha256sum
```

To get the value
