### ISSUE TITLE
APN push delivered but the device itself does not refresh/check mail

### ISSUE THREAD

**Issue by titanism** [scintill/macos-server-apns-certs#7]
Hi there,

We've implemented the approach as similar to Dovecot at <https://github.com/nodemailer/wildduck/issues/711> however the APN payload (e.g. `{ aps: { 'account-id': '....' } }`) gets successfully delivered BUT the device itself does not get the push notification nor does it refresh the inbox on the device.  Thanks for providing `vendorcerts/` and detailed instructions in README btw 🙏 

Is there some other approach required?  Or is Fastmail and Yahoo the only ones permitted to do this?

Thank you,

cc @scintill 

(we're the team from Forward Email (@forwardemail) https://forwardemail.net 🚀 )

**Comment by scintill** [comment]
Glad you got it working 👍
